version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - run: 
          command: |
            mkdir -p ~/reports
            eslint ./client/ --format junit --output-file ~/reports/eslintCli.xml
            eslint ./server/ --format junit --output-file ~/reports/eslintServ.xml
            eslint ./database/ --format junit --output-file ~/reports/eslintDb.xml
            eslint ./seeding/ --format junit --output-file ~/reports/eslintSeed.xml
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports